### ISSUE TITLE
Events don't respond to direct changes to the "document"

### ISSUE THREAD

**Issue by NathanSmutz** [reagent-project/reagent-forms#101]
The readme says this about the behavior of events:

> Events are triggered whenever the document is updated, and will be executed in the order they are listed. Each event sees the document modified by its predecessor.

I'm not seeing an event trigger when the bound atom (the "document") is updated via swap! or via another event.  It responds as expected when text is typed into the form.

**Comment by yogthos** [comment]
The events have to be added as described [here](https://github.com/reagent-project/reagent-forms#adding-events). The form will not updated when the atom is manipulated externally however.
