### ISSUE TITLE
Possible addition to readme: Events: id as a sequence

### ISSUE THREAD

**Issue by NathanSmutz** [reagent-project/reagent-forms#102]
I presume this is because my form has multiple inputs:

Having bound an event like (fn [id value document] ...)
For a fom input :item, id would be bound to (:item) rather than :item

**Comment by yogthos** [comment]
right each id is converted to a path in the document, so for :item you'd get (:item), but for :person.name you'd get (:person :name)

**Comment by NathanSmutz** [comment]
I wonder if the example in readme needs to change:

[bind-fields
  form-template
  doc
  (fn [id value {:keys [weight height] :as doc}]
    (when (and (some #{id} [:height :weight]) weight height)
      (assoc-in doc [:bmi] (/ weight (* height height)))))]

With an event on :weight, (some #{id} [:height :weight]) would evaluate to:(some #{(:weight)} [:height :weight])

The Events section in the readme seems to imply that bare keywords are passed.  Is there a case where that happens?

**Comment by yogthos** [comment]
The id gets translated to a path [here](https://github.com/reagent-project/reagent-forms/blob/774dff42a990e6493abea6fbaba5d08eee55502e/src/reagent_forms/core.cljs#L24). So you should be able to supply an id such as `:person.name` for a nested path.
