### ISSUE TITLE
date picker formatting

### ISSUE THREAD

**Issue by aaronblenkush** [reagent-project/reagent-forms#121]
The "date of birth" field in the [demo](http://yogthos.github.io/reagent-forms-example.html) doesn't seem to be formatted correctly.

![image](https://user-images.githubusercontent.com/963760/29643463-2601b33a-8824-11e7-9c03-0a8da7f64e90.png)

**Comment by yogthos** [comment]
looks like this issue came back https://github.com/reagent-project/reagent-forms/issues/31

I won't have time to take a look in the near future, but I could definitely help with a pr and a release if you can take a look at the styling.

**Comment by yogthos** [comment]
Also, looks like the problem is strictly in the demo. The latest version works correctly.
