### ISSUE TITLE
Redundant  `valid-number-ending?` function?

### ISSUE THREAD

**Issue by smogg** [reagent-project/reagent-forms#130]
I don't understand the purpose of this function and I'd appreciate some clarification: https://github.com/reagent-project/reagent-forms/blob/master/src/reagent_forms/core.cljs#L106

**Comment by yogthos** [comment]
Doesn't look like it's being used anymore, and can be removed (I just pushed an update for that). If I recall correctly it was used to check whether formatting should be applied to a numeric field. Original approach was to only show the formatted input, but later on I switched to showing the original input if it couldn't be parsed into a number.
