### ISSUE TITLE
:validator bug

### ISSUE THREAD

**Issue by camachom** [reagent-project/reagent-forms#142]
Hello! Thanks for maintaining this awesome library. I'm using 5.38, and experienced some unexpected behavior with `:validator`. It works great if you have a plain input like this:
```cloure
[:input.form-control
     {:validator some-func
      :field :text
      :id id}]
```
However, if you're using `class` attribute, appending the new classes erases the old ones:
```cloure
[:input.form-control
     {:class ["foo" "bar"]
      :validator some-func
      :field :text
      :id id}]
```
Anything in the vector ["foo" "bar"] will no longer show up, but `form-control` is still there. When I inspect the input, an object shows up: `(#object[G__10589] "foo")`. Let me know if you're able to reproduce the behavior.

**Comment by yogthos** [comment]
Thanks for the report, I just pushed out 0.5.39 with a fix. Let me know if it looks good to you.

**Comment by camachom** [comment]
seems to work just fine. Thanks!
