### ISSUE TITLE
:numeric not updating state

### ISSUE THREAD

**Issue by camachom** [reagent-project/reagent-forms#143]
Hi again!

I'm trying to use `:numeric` on an input filed. However, the resulting `input` tag is still labeled as `text`, and the state is not updated `on-change`.  Something like this:
```clojure
    [:input.form-control
     {:class class
      :validator error-handler
      :field :numeric
      :id id}]
```
If I change it back to `text`, it works fine. Let me know if you can reproduce.

**Comment by yogthos** [comment]
I pushed out a new version with the `:numeric` changed to an HTML 5 number input. Seems to be working as expected locally, let me  know if it looks good.

**Comment by camachom** [comment]
Sorry for the delayed response. Yes, it worked really well for me. Thanks!
