### ISSUE TITLE
The October's short name missing from the Datepicker's Finnish locales

### ISSUE THREAD

**Issue by aleksiromanov** [reagent-project/reagent-forms#145]
The Datapicker component uses a map of locales for several languages. Because the October's short name entry Finnish (fi-FI) locales is missing by mistake, a row is missing from the Dtapicker's months-dropdown list as well. In Finnish, the commonly used short name for October is Loka.

1. At the moment:

$ git br -v
* master 583078d Unbalanced vector in re-frame example (#144)

$ grep :months-short.*Tammi.*Helmi src/reagent_forms/datepicker.cljs
:months-short ["Tammi" "Helmi" "Maalis" "Huhti" "Touko" "Kesä" "Heinä" "Elo" "Syys" "Marras" "Joulu"]

2. Fix (insert missing Loka between Syys and Marras):

$ sed -i 's/"Syys" "Marras"/"Syys" "Loka" "Marras"/' src/reagent_forms/datepicker.cljs

3. Fixed version:

$ grep :months-short.*Tammi.*Helmi src/reagent_forms/datepicker.cljs
:months-short ["Tammi" "Helmi" "Maalis" "Huhti" "Touko" "Kesä" "Heinä" "Elo" "Syys" "Loka" "Marras" "Joulu"]

**Comment by aleksiromanov** [comment]
I will do this

**Comment by yogthos** [comment]
pushed out a new release with the fix
