### ISSUE TITLE
Add table of contents to README?

### ISSUE THREAD

**Issue by efraimmgon** [reagent-project/reagent-forms#149]
I'm using reagent-forms again after a long time and I'm referring to the README a lot. 

The issue is that I'm using cmd + f to navigate the page, and I find that if it had a table of contents perhaps it would be easier to find what I need.

If this is found to be useful I can help with it.

**Comment by yogthos** [comment]
Yeah that would be pretty handy. The README has grown quite a bit, so having a toc would make it a lot more usable. If you have a chance to help with it, a PR would be very welcome. :)

**Comment by efraimmgon** [comment]
Ok, just created it: https://github.com/reagent-project/reagent-forms/pull/150.
