### ISSUE TITLE
Datepicker dropdown container

### ISSUE THREAD

**Issue by pepa-linha** [reagent-project/reagent-forms#156]
Is it possible change dropdown DOM element parent? I would like to place a dropdown (element `<div class="datepicker dp-dropdown">`) in a document body (`<body>`), for example, because my dropdown parent has `overflow: auto` which causes a cut the dropdown element.
Thanks.

**Comment by yogthos** [comment]
There isn't any easy way to do this, but you could potentially do this using `component-did-mount` lifecycle method where you'd have access to the actual mounted DOM that you can manipulate.

**Comment by pepa-linha** [comment]
Ok, thanks so much for 🚀 answer.
