### ISSUE TITLE
Datepicker on Firefox looks strange

### ISSUE THREAD

**Issue by faenvie** [reagent-project/reagent-forms#31]
Hi, 

see, how datepicker looks on my Firefox:

http://littlelambda.com/snaps/reagent-forms-datepicker-on-firefox.png

i am running uptodate Firefox on Ubuntu 12.04 without any modifications

http://littlelambda.com/snaps/firefox-on-ubuntu1204.png 
  
it maybe worth taking a look, if someone else could confirm the issue. 

thanks for reagent & tools

**Comment by faenvie** [comment]
Same with the live-demo http://yogthos.github.io/reagent-forms-example.html

Looks Ok on same machines Chromium :)

**Comment by yogthos** [comment]
Hmm, it looks like FF interprets the CSS in a funny way.

**Comment by luposlip** [comment]
It looks funny in IE 11.0.9600.17280IS too: 
![2015-05-06 13_09_49-reagent-forms examples - internet explorer](https://cloud.githubusercontent.com/assets/763627/7492186/7c02d94a-f3f1-11e4-9b1f-4cf2f146d090.png)

**Comment by yogthos** [comment]
yeah it looks like css might need some work outside chrome :)

**Comment by yogthos** [comment]
fixed by https://github.com/reagent-project/reagent-forms/pull/96
