### ISSUE TITLE
Checkbox not linked to the 'checked' attribute

### ISSUE THREAD

**Issue by Quantisan** [reagent-project/reagent-forms#40]
When I default check a checkbox with `[:input {:type :checkbox :checked true}]`, user can't manually uncheck it. It appears that the [checkbox value is not updated by check/uncheck](http://facebook.github.io/react/docs/two-way-binding-helpers.html). So right now I'm just hacking it with an atom state and doing `:on-click` to swap the attribute. Is that the recommended way?

Any suggestion on how to get checkbox to just work out of the box with reagent-forms? I can submit a pull request if you give me some pointers.

**Comment by yogthos** [comment]
Sounds like you just have to handle the additional case for the state of the [checkbox component](https://github.com/reagent-project/reagent-forms/blob/c9de0c538a736080666bbfbd8500a33c91a5d592/src/reagent_forms/core.cljs#L83). A pr sounds great, let me know if you need any additional pointers with it.

**Comment by Quantisan** [comment]
Turns out there's a `defaultChecked` property that should have been used. This works out of the box:

```
[:input {:type :checkbox :name :foo :value true :defaultChecked true}]
```
