### ISSUE TITLE
Collection editor

### ISSUE THREAD

**Issue by yayitswei** [reagent-project/reagent-forms#44]
How would I create a set of text boxes, with each textbox editing a value in a vector, and the ability to add/subtract elements?

Since the template is evaluated eagerly, I can't generate the text boxes directly from the vector.

**Comment by yogthos** [comment]
The best way at the moment would be to create a new `defmethod` for `init-field` as described in the custom fields section in the readme.

The element could then keep an atom for the local state, i.e. current element. Then on change it would populate the doc with the result. The [typeahead](https://github.com/reagent-project/reagent-forms/blob/65cc1fb50c132bfeef1b44d1e8c1d7677730914a/src/reagent_forms/core.cljs#L189) element is an example of a similar behavior.

**Comment by yayitswei** [comment]
Thanks for the suggestion, that approach is working for me so far.

Why do get and save work inside of the `render-element` form, but dereferencing the source atom doesn't, for updating the view based on the source data?

**Comment by yogthos** [comment]
If you're referencing the atom inside on the `:field` elements that will likely get lost since `bind-field` will create a new component. However, it's generally better to use `get` and `save!` functions as they will trigger events.
