### ISSUE TITLE
Placeholder attribute

### ISSUE THREAD

**Issue by deadghost** [reagent-project/reagent-forms#53]
A placeholder key should be available. For example:

    [:div {:field :datepicker
           :id :date
           :date-format "mm/dd/yyyy"
           :placeholder "Date"}]

should result in:

    ...
    <input 
      placeholder="Date" 
      readonly="" 
      class="form-control" 
      data-reactid=".0.0.0.0.0.0.0.0" 
      type="text">
    ...

**Comment by yogthos** [comment]
should be fixed in `0.5.1`, just pushed to clojars
