### ISSUE TITLE
:disabled option should take a function

### ISSUE THREAD

**Issue by erikcw** [reagent-project/reagent-forms#59]
The `:disabled` option for fields should take a function, similar to `:visible?` so that a field's disabled status can be changed dynamically as other form elements modify the contents of the `atom`.

**Comment by yogthos** [comment]
That sounds reasonable, would you be up for doing a pr by any chance? :)

**Comment by erikcw** [comment]
Sure, no problem.

**Comment by yogthos** [comment]
excellent :)

**Comment by smogg** [comment]
It's been a while and I don't think this was ever implemented. Would you accept a PR @yogthos? My first thought is to implement it in `reagent-forms.macros/render-element`.

**Comment by yogthos** [comment]
yeah definitely

**Comment by smogg** [comment]
I think this can be closed since #125 and #126 were merged
