### ISSUE TITLE
Radio buttons that start selected should add their value to the state

### ISSUE THREAD

**Issue by lvh** [reagent-project/reagent-forms#74]
Right now, when you use radio buttons and one of them is selected by default, nothing is written to the state, e.g.:

```clojure
[:input {:field :radio :value :a :name :radioselection} "foo"]
[:input {:field :radio :value :b :name :radioselection :checked true} "bar"]
[:input {:field :radio :value :c :name :radioselection} "baz"]
```

... will not write `:radioselection :b` to the state. It seems like it should. Assuming it should; I'd be happy to contribute a PR.

**Comment by yogthos** [comment]
Yeah that makes sense, I've just pushed out a new version with a fix, also updated checkboxes to support the same behavior.

**Comment by lvh** [comment]
Awesome! Thank you!

**Comment by lvh** [comment]
I'm guessing this can be closed now since it's fixed in master?
