### ISSUE TITLE
Reagent-forms demo site shows blank page

### ISSUE THREAD

**Issue by dpetranek** [reagent-project/reagent-forms#77]
Navigating to the reagent forms demo page linked from the repo README shows a blank page. I'm using Firefox 42.0 on Windows 7 64-bit. Also on Google Chrome Canary.
![reagent-forms-demo](https://cloud.githubusercontent.com/assets/2993946/11514998/04795f12-9841-11e5-803b-4ea179515b26.png)

**Comment by dpetranek** [comment]
But it does work on Internet Explorer 11, huh.

**Comment by yogthos** [comment]
Hmm interesting, I'm ok viewing it in chrome on os x, but latest ff barfs on it here as well. I'll take a look at some point. Might just be a matter of updating the dependencies.

**Comment by binarykitchen** [comment]
Just open the dev console. Error is `uncaught exception: Invalid match arg: /\./`

**Comment by yogthos** [comment]
so ff Js implementation handles regex differently?

**Comment by tpatja** [comment]
OSX 10.11, Chrome  48.0.2564.103, shows blank page.
`Uncaught Invalid match arg: /\./`

**Comment by yogthos** [comment]
yup, can reproduce, I guess I'll have to make a new build for it :)

**Comment by yogthos** [comment]
ok it's back in working order :)
