### ISSUE TITLE
Consider using `input` event rather than `change`

### ISSUE THREAD

**Issue by eyelidlessness** [reagent-project/reagent-forms#78]
The current behavior of `bind-fields` uses the `change` event to update bindings. The [behavior](https://developer.mozilla.org/en-US/docs/Web/Events/change) of the `change` event is such that the state will not update until a form field is blurred. This means that, for forms with an `:onSubmit` handler, if a user presses enter within a modified form field, the state of the bound atom will reflect its old value.

The [`input` event](https://developer.mozilla.org/en-US/docs/Web/Events/input) (supported by all modern browsers, IE9+) would fire anytime the input value changes, thereby ensuring the bound atom is never out of sync.

**Comment by yogthos** [comment]
That makes sense, would you be up for making a pr for this?

**Comment by eyelidlessness** [comment]
I'd love to. Is the browser support baseline acceptable?

**Comment by yogthos** [comment]
Yeah definitely, can just add a note in the readme that this works with ie9+.
