### ISSUE TITLE
validation states error message

### ISSUE THREAD

**Issue by teaforthecat** [reagent-project/reagent-forms#80]
Any thoughts on how we could add an error message or change the label of a field depending on the validation state? I'm thinking it would be another field type like this `[:div {:field :error}]`, adding to the `bind` and `init-field` multi-methods. Does that sound right? This idea would be in correlation with #62

**Comment by yogthos** [comment]
yeah that should work, sounds similar to the [alert element](https://github.com/reagent-project/reagent-forms#alert)

**Comment by teaforthecat** [comment]
In taking a second look, it looks like the :label field would work. Here's what I came up with:
```
[:label.control-label {:for id :placeholder label :id [:errors id :label] :field :label}]
```
Also when the label shouldn't change, and you just want an inline error message:
```
[:div.error_message {:field :label :id [:errors id :message] }]
```
Pretty simple, no change needed. Thanks!

**Comment by yogthos** [comment]
excellent :)
