### ISSUE TITLE
Allow custom names for months/day-of-week for datepicker

### ISSUE THREAD

**Issue by dmarjenburgh** [reagent-project/reagent-forms#84]
I would like to pass a custom map with month names, short-month names and day-of-week names.
This way, each user can implement localised names easily.

I have a working example here. Would you be interested in supporting this behaviour?
https://github.com/reagent-project/reagent-forms/compare/master...dmarjenburgh:custom-month-names

**Comment by yogthos** [comment]
I don't see any downsides :)

**Comment by Jaaqo** [comment]
+1, I need to translate the names aswell.

**Comment by yogthos** [comment]
@dmarjenburgh any chance you'd be interested in doing a pr for this?

**Comment by jaaqo** [comment]
@yogthos would you be interested in something like this? 7735d021f857afe73ad4c0e864916c91637d1f10

Basically same as dmarjenburghs but with some built in translations for ease of use

**Comment by yogthos** [comment]
@jaaqo yeah that looks good to me

**Comment by dmarjenburgh** [comment]
:+1

**Comment by yogthos** [comment]
this pr should do it https://github.com/reagent-project/reagent-forms/pull/91 and I've pushed the latest to Clojars
