### ISSUE TITLE
Datepicker wrapped in label

### ISSUE THREAD

**Issue by hosiawak** [reagent-project/reagent-forms#86]
If a datepicker input is wrapped in a `[:label]` it disappears as soon as **any** of its buttons are clicked. I presume it's because the datepicker div itself is wrapped in the label and its clicks get propagated up to the label and then from the label down to the input field (browser behaviour). This makes it `(swap! expanded? not)` and it disappears.

I think the fix is to add e.stopPropagation to every `:on-click` handler in datepicker but I need to check

```clojure
(def form
  [:form
   [:label
    [:input {:field :datepicker :id :test}]]])

(defn main []
  (let [doc (r/atom {})]
    (fn []
      [:div
       [:h1 (str "Doc: " @doc)]
       [bind-fields form doc]])))```

**Comment by yogthos** [comment]
That sounds like the problem, would you be up for doing a pr for this?

**Comment by hosiawak** [comment]
I would but I have no idea how to import this project tbh so that I can use it locally (Clojure newbie). I have a fork on GH, I can check it out but then what should I do to test it locally ?

**Comment by yogthos** [comment]
All you have to do to run it locally is run `lein install` once you check it out. That puts a local jar in your `~/.m2/repository/` folder and that'll get picked up when you use it as a dependency.
