### ISSUE TITLE
What a fuck is this bind-fields ? 

### ISSUE THREAD

**Issue by NoWayHoze** [reagent-project/reagent-forms#94]
(fn []
      [:div
       [:div.padding]

       [:div.page-header [:h1 "Sample Form"]]

       [editor
        doc
        [bind-fields

**Comment by yogthos** [comment]
it's described in the documentation [right here](https://github.com/reagent-project/reagent-forms#binding-the-form-to-a-document)

**Comment by NoWayHoze** [comment]
thanks

Date: Sun, 21 Feb 2016 20:59:31 -0800

**Comment by NoWayHoze** [comment]
Excuse me again...
How about this, edn->hiccuphow does this end to your code ?
I can't see any dependency or require to meet this, not in your tutorial, not in your source code ?

-Markus



Date: Sun, 21 Feb 2016 20:59:31 -0800

**Comment by lacarmen** [comment]
It generates a DOM node representing [edn](https://github.com/edn-format/edn) encoded data. The documentation is [here](https://github.com/yogthos/json-html).

It's being used to generate the document state preview in the [demo](https://yogthos.github.io/reagent-forms-example.html)
